### ISSUE TITLE
possibility to share database over multiple computers

### ISSUE THREAD

**Issue by wullxz** [substack/clocker#12]
Any ideas How to use one clocker db on multiple computers? 
I'd like to be able to Start and end one Task on different computers and keep the records synchronized on all computers.
Maybe this is easy solvable with a config File and the possibility to specify a custom db Directory?

**Comment by fnogatz** [comment]
By [specifying](https://github.com/substack/clocker/blob/master/bin/cmd.js#L18) the `HOME` or `USEPROFILE` environment variable it is possible to set the database directory to any shared space. I don't think it is on the roadmap to implement some kind of distributed database backend.
