### ISSUE TITLE
Support `clocker set start '-10 minutes'`

### ISSUE THREAD

**Issue by fnogatz** [substack/clocker#27]

**Comment by yoshuawuyts** [comment]
Could you elaborate a little more on what this does?

**Comment by fnogatz** [comment]
Sometimes (way too often! :smile:) I forget to start the clocker. Then I do the following commands:

```
clocker start -t Work
clocker set start '11:10'
```

The start time is an estimate - most time I simply look at the current time, say "Uhm, I think I started then minutes ago" and use this time.

**Comment by yoshuawuyts** [comment]
!!! neat idea  !!! 😁🍉

**Comment by nevilgeorge** [comment]
has someone claimed this? If not, can I give it a shot?

**Comment by yoshuawuyts** [comment]
@nevilgeorge go for it

**Comment by nevilgeorge** [comment]
will do (Y). If I have any questions, I'll let you know!

**Comment by fnogatz** [comment]
Nice :)

I was unsure about distinguishing the following two use cases:

1. "Set the start time to 10 minutes before the currently stored start time"
1. "Set the start time to 10 minutes ago (as of now)"

I am not sure which use case is more common. The "-10 minutes" seems a little bit more like version 1, while "10 minutes ago" seems to be more appropriate for version 2. The latter one could be realized using [parse-messy-time](https://github.com/substack/parse-messy-time).

Your opinions?

**Comment by nevilgeorge** [comment]
The first use case didn't even come to my mind -- I was only of thinking of the second use case. It may be nice to have both of them, though. @yoshuawuyts what are your thoughts?

**Comment by yoshuawuyts** [comment]
`10 minutes ago` would be nice.

**Comment by nevilgeorge** [comment]
I'm working on this now, and just wanted some clarification on the API. Are we expecting it to be `clocker set start '-10'` or `clocker set start '-10 minutes/hours'` `clocker set start '-10 minutes ago'`.  Let me know what you think will be best!

**Comment by fnogatz** [comment]
As of now, things like `10 minutes ago`, `10min ago`, etc., are supported via [parse-messy-time](https://github.com/substack/parse-messy-time). So everything's done here.
