### ISSUE TITLE
semver major problems

### ISSUE THREAD

**Issue by substack** [substack/clocker#51]
It seems like a lot of things are broken now in a refactor, but the semver major version was not updated accordingly?

**Comment by fnogatz** [comment]
Our aim in the rewrite of #40 was to not break any CLI at all, but apparently we missed some rarely used options. I would consider this a bug, and re-adding the accidentally removed items therefore only as *PATCH* according to semver.

**Comment by fnogatz** [comment]
What was reported to be missing after the refactoring was resolved in the meantime, so I will close this issue here.
